[FUSE-52] - Implements CRUD for Campaign and Package Service
Ky7Org/weight-loss-consultant pull request #29
Opened 2021-09-30 10:56 UTC by CaoSon1909

- Implements CRUD for Campaign and Package Service
- Improve authentication service (bring it back to right place and add response body)

2021-09-30 11:43 UTC, TienTruong209 requested changes
Please remove all "any" type except in Generic classes

2021-09-30 11:43 UTC, TienTruong209 commented on apps/weight-loss-consultant-packages-mgnt-api/src/app/controllers/campaign.controller.ts
> +  async index(@Res() res): Promise<any> {
Please add Swagger for this endpoint

2021-09-30 11:43 UTC, TienTruong209 commented on apps/weight-loss-consultant-packages-mgnt-api/src/app/controllers/campaign.controller.ts
> +      console.error(e);
Should not console.error here, please use NestJS built-in logger

2021-09-30 11:43 UTC, TienTruong209 commented on apps/weight-loss-consultant-packages-mgnt-api/src/app/controllers/package.controller.ts
> +  async update(@Param('id') id : number, @Body() dto: UpdatePackageDto, @Res() res): Promise<any> {
Please provide a ResponseModel rather than using any

2021-09-30 11:43 UTC, TienTruong209 commented on apps/weight-loss-consultant-packages-mgnt-api/src/main.ts
> +    .setTitle('Loss weigth consultant')
Misspell "weight"

2021-10-04 17:46 UTC, bangmaple commented
LGTM

2021-10-04 17:46 UTC, merged